spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope:
              - email
              - profile

cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-southeast-1
    stack:
      auto: false

application:
  bucket:
    name: fpt-e-resources
